/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as GranskaRouteRouteImport } from './routes/granska/route'
import { Route as InbjudanRouteImport } from './routes/inbjudan'
import { Route as LoggaInRouteImport } from './routes/logga-in'
import { Route as OrganisationRouteRouteImport } from './routes/organisation/route'
import { Route as TvafaktorRouteImport } from './routes/tvafaktor'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as DevFigurRouteImport } from './routes/dev/figur'
import { Route as DevIdentitetRouteImport } from './routes/dev/identitet'
import { Route as DevUiRouteImport } from './routes/dev/ui'
import { Route as GranskaIndexRouteImport } from './routes/granska/index'
import { Route as OrganisationIndexRouteImport } from './routes/organisation/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const GranskaRouteRoute = GranskaRouteRouteImport.update({
  id: '/granska',
  path: '/granska',
  getParentRoute: () => rootRouteImport,
} as any)
const InbjudanRoute = InbjudanRouteImport.update({
  id: '/inbjudan',
  path: '/inbjudan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoggaInRoute = LoggaInRouteImport.update({
  id: '/logga-in',
  path: '/logga-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisationRouteRoute = OrganisationRouteRouteImport.update({
  id: '/organisation',
  path: '/organisation',
  getParentRoute: () => rootRouteImport,
} as any)
const TvafaktorRoute = TvafaktorRouteImport.update({
  id: '/tvafaktor',
  path: '/tvafaktor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const DevFigurRoute = DevFigurRouteImport.update({
  id: '/dev/figur',
  path: '/dev/figur',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIdentitetRoute = DevIdentitetRouteImport.update({
  id: '/dev/identitet',
  path: '/dev/identitet',
  getParentRoute: () => rootRouteImport,
} as any)
const DevUiRoute = DevUiRouteImport.update({
  id: '/dev/ui',
  path: '/dev/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const GranskaIndexRoute = GranskaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GranskaRouteRoute,
} as any)
const OrganisationIndexRoute = OrganisationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganisationRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/granska': typeof GranskaRouteRouteWithChildren
  '/organisation': typeof OrganisationRouteRouteWithChildren
  '/inbjudan': typeof InbjudanRoute
  '/logga-in': typeof LoggaInRoute
  '/tvafaktor': typeof TvafaktorRoute
  '/dev/figur': typeof DevFigurRoute
  '/dev/identitet': typeof DevIdentitetRoute
  '/dev/ui': typeof DevUiRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/granska/': typeof GranskaIndexRoute
  '/organisation/': typeof OrganisationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inbjudan': typeof InbjudanRoute
  '/logga-in': typeof LoggaInRoute
  '/tvafaktor': typeof TvafaktorRoute
  '/dev/figur': typeof DevFigurRoute
  '/dev/identitet': typeof DevIdentitetRoute
  '/dev/ui': typeof DevUiRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/granska': typeof GranskaIndexRoute
  '/organisation': typeof OrganisationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/granska': typeof GranskaRouteRouteWithChildren
  '/organisation': typeof OrganisationRouteRouteWithChildren
  '/inbjudan': typeof InbjudanRoute
  '/logga-in': typeof LoggaInRoute
  '/tvafaktor': typeof TvafaktorRoute
  '/dev/figur': typeof DevFigurRoute
  '/dev/identitet': typeof DevIdentitetRoute
  '/dev/ui': typeof DevUiRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/granska/': typeof GranskaIndexRoute
  '/organisation/': typeof OrganisationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/granska'
    | '/organisation'
    | '/inbjudan'
    | '/logga-in'
    | '/tvafaktor'
    | '/dev/figur'
    | '/dev/identitet'
    | '/dev/ui'
    | '/admin/'
    | '/app/'
    | '/granska/'
    | '/organisation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inbjudan'
    | '/logga-in'
    | '/tvafaktor'
    | '/dev/figur'
    | '/dev/identitet'
    | '/dev/ui'
    | '/admin'
    | '/app'
    | '/granska'
    | '/organisation'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/granska'
    | '/organisation'
    | '/inbjudan'
    | '/logga-in'
    | '/tvafaktor'
    | '/dev/figur'
    | '/dev/identitet'
    | '/dev/ui'
    | '/admin/'
    | '/app/'
    | '/granska/'
    | '/organisation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  GranskaRouteRoute: typeof GranskaRouteRouteWithChildren
  OrganisationRouteRoute: typeof OrganisationRouteRouteWithChildren
  InbjudanRoute: typeof InbjudanRoute
  LoggaInRoute: typeof LoggaInRoute
  TvafaktorRoute: typeof TvafaktorRoute
  DevFigurRoute: typeof DevFigurRoute
  DevIdentitetRoute: typeof DevIdentitetRoute
  DevUiRoute: typeof DevUiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/granska': {
      id: '/granska'
      path: '/granska'
      fullPath: '/granska'
      preLoaderRoute: typeof GranskaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbjudan': {
      id: '/inbjudan'
      path: '/inbjudan'
      fullPath: '/inbjudan'
      preLoaderRoute: typeof InbjudanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logga-in': {
      id: '/logga-in'
      path: '/logga-in'
      fullPath: '/logga-in'
      preLoaderRoute: typeof LoggaInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisation': {
      id: '/organisation'
      path: '/organisation'
      fullPath: '/organisation'
      preLoaderRoute: typeof OrganisationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tvafaktor': {
      id: '/tvafaktor'
      path: '/tvafaktor'
      fullPath: '/tvafaktor'
      preLoaderRoute: typeof TvafaktorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/dev/figur': {
      id: '/dev/figur'
      path: '/dev/figur'
      fullPath: '/dev/figur'
      preLoaderRoute: typeof DevFigurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/identitet': {
      id: '/dev/identitet'
      path: '/dev/identitet'
      fullPath: '/dev/identitet'
      preLoaderRoute: typeof DevIdentitetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/ui': {
      id: '/dev/ui'
      path: '/dev/ui'
      fullPath: '/dev/ui'
      preLoaderRoute: typeof DevUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/granska/': {
      id: '/granska/'
      path: '/'
      fullPath: '/granska/'
      preLoaderRoute: typeof GranskaIndexRouteImport
      parentRoute: typeof GranskaRouteRoute
    }
    '/organisation/': {
      id: '/organisation/'
      path: '/'
      fullPath: '/organisation/'
      preLoaderRoute: typeof OrganisationIndexRouteImport
      parentRoute: typeof OrganisationRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface GranskaRouteRouteChildren {
  GranskaIndexRoute: typeof GranskaIndexRoute
}

const GranskaRouteRouteChildren: GranskaRouteRouteChildren = {
  GranskaIndexRoute: GranskaIndexRoute,
}

const GranskaRouteRouteWithChildren = GranskaRouteRoute._addFileChildren(
  GranskaRouteRouteChildren,
)

interface OrganisationRouteRouteChildren {
  OrganisationIndexRoute: typeof OrganisationIndexRoute
}

const OrganisationRouteRouteChildren: OrganisationRouteRouteChildren = {
  OrganisationIndexRoute: OrganisationIndexRoute,
}

const OrganisationRouteRouteWithChildren =
  OrganisationRouteRoute._addFileChildren(OrganisationRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  GranskaRouteRoute: GranskaRouteRouteWithChildren,
  OrganisationRouteRoute: OrganisationRouteRouteWithChildren,
  InbjudanRoute: InbjudanRoute,
  LoggaInRoute: LoggaInRoute,
  TvafaktorRoute: TvafaktorRoute,
  DevFigurRoute: DevFigurRoute,
  DevIdentitetRoute: DevIdentitetRoute,
  DevUiRoute: DevUiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
